name: salus
channels:
  - galaxy001
  - nvidia
  - salus
  - pytorch
  - conda-forge
  - pyg
  - bioconda
  - https://software.repos.intel.com/python/conda/
  - tiledb
  - nodefaults
dependencies:
  - bioconda::htseq
  - bioconda::mappy
  - bioconda::pyfastx
  - bioconda::pysam
  - bioconda::snakemake-wrapper-utils[version='>=0.6.2']
  - conda-forge::cellpose
  - conda-forge::click
  - conda-forge::colour-science
  - conda-forge::cython
  - conda-forge::lightning
  - conda-forge::pip
  - conda-forge::python[version='>=3.11']
  - conda-forge::torchmetrics
  - conda-forge::cykhash
  - conda-forge::dask
  - conda-forge::dask-image
  - conda-forge::fa2
  - conda-forge::fast_matrix_market
  - conda-forge::findiff
  - galaxy001::dinopy
  - galaxy001::mplcairo
  - galaxy001::pretty_errors
  - galaxy001::salusts
  - galaxy001::scselpy
  - galaxy001::segment_anything
  - galaxy001::stagate_pyg
  - conda-forge::gawk
  - conda-forge::hmmlearn
  - conda-forge::ipykernel
  - conda-forge::leidenalg
  - conda-forge::lxml
  - conda-forge::markdown
  - conda-forge::matplotlib-base
  - conda-forge::matspy
  - conda-forge::minify-html
  - conda-forge::mpl-scatter-density
  - conda-forge::natsort
  - conda-forge::networkx[default]
  - conda-forge::numba
  - conda-forge::numdifftools
  - conda-forge::numpy
  - conda-forge::pandas
  - conda-forge::pillow
  - conda-forge::plotly
  - conda-forge::polars
  - conda-forge::prettytable
  - conda-forge::py-opencv=*[build=headless_*]
  - conda-forge::pyarrow[version='<16']
  - conda-forge::pycairo
  - pyg::pyg
  - pyg::pytorch-scatter
  - pyg::pytorch-sparse
  - conda-forge::pygraphviz
  - conda-forge::pymdown-extensions
  - conda-forge::pyqtgraph[version='>=0.11.1']
  - conda-forge::python-graphblas
  - conda-forge::python-igraph
  - conda-forge::python-isal
  - conda-forge::python-kaleido
  - conda-forge::python-suitesparse-graphblas
  - conda-forge::python-zlib-ng
  - pytorch::pytorch[version='>=2.1']
  - pytorch::torchvision
  - conda-forge::pyyaml
  - conda-forge::qtpy
  - conda-forge::recordclass
  - conda-forge::scanpy[version='>=1.9.8']
  - conda-forge::scikit-learn
  - conda-forge::scikit-misc
  - conda-forge::scipy
  - conda-forge::seaborn
  - conda-forge::setuptools>=61
  - conda-forge::squidpy
  - conda-forge::statsmodels
  - conda-forge::stopit
  - conda-forge::superqt
  - conda-forge::tifffile
  - tiledb::tiledbsoma-py
  - conda-forge::tqdm
  - conda-forge::weasyprint
  - conda-forge::xopen
  - conda-forge::bash
  - bioconda::bwa-mem2
  - bioconda::cutadapt
  - bioconda::fastp[version='>=0.23.4']
  - bioconda::fgbio-minimal[version='>=2.2.0']
  - bioconda::gtftools
  - bioconda::mbuffer
  - bioconda::picard-slim
  - bioconda::samblaster
  - bioconda::samtools[version='>=1.17']
  - bioconda::seqkit[version='>=2.5.1']
  - bioconda::seqtk
  - bioconda::snakemake[version='>=7.17.0']
  - conda-forge::conda
  - conda-forge::fastremap
  - galaxy001::fastp_salus
  - galaxy001::salusts_bwamem2bcorrect
  - galaxy001::salusts_cbrna
  - galaxy001::salusts_saluscbmap
  - galaxy001::salusts_saturation-plot
  - galaxy001::salusts_tif2mtx
  - conda-forge::imagecodecs
  - mkl==2024.0.0
  - tbb[version='>=2021.11']
  - conda-forge::kernel-headers_linux-64[version='>=4']
  - conda-forge::llvmlite
  - conda-forge::nodejs
  - conda-forge::open-fonts
  - conda-forge::openssh
  - conda-forge::parallel
  - conda-forge::pigz
  - conda-forge::pkg-config
  - conda-forge::roifile
  - salus::starsalus[version='>=2.7']
  - conda-forge::tsv-utils
  - conda-forge::unzip
  - conda-forge::yq
  - conda-forge::zstd
  - pytorch::pytorch-cuda[version='>=12.1']
  - pytorch::pytorch-mutex=*[build=cuda]
  - conda-forge::cuda-cudart
  - conda-forge::cuda-version=12

# micromamba create -n salus; micromamba install -n salus --file environmentGPU.yml

